# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_insertar.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 190, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 260, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_precio = QtWidgets.QLabel(self.centralwidget)
        self.label_precio.setGeometry(QtCore.QRect(60, 340, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_precio.setFont(font)
        self.label_precio.setObjectName("label_precio")
        self.insertar_prenda = QtWidgets.QLineEdit(self.centralwidget)
        self.insertar_prenda.setGeometry(QtCore.QRect(320, 60, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.insertar_prenda.setFont(font)
        self.insertar_prenda.setObjectName("insertar_prenda")
        self.insertar_talla = QtWidgets.QLineEdit(self.centralwidget)
        self.insertar_talla.setGeometry(QtCore.QRect(320, 120, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.insertar_talla.setFont(font)
        self.insertar_talla.setObjectName("insertar_talla")
        self.insertar_color = QtWidgets.QLineEdit(self.centralwidget)
        self.insertar_color.setGeometry(QtCore.QRect(320, 200, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.insertar_color.setFont(font)
        self.insertar_color.setObjectName("insertar_color")
        self.insertar_temporada = QtWidgets.QLineEdit(self.centralwidget)
        self.insertar_temporada.setGeometry(QtCore.QRect(320, 270, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.insertar_temporada.setFont(font)
        self.insertar_temporada.setObjectName("insertar_temporada")
        self.insertar_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.insertar_precio.setGeometry(QtCore.QRect(320, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.insertar_precio.setFont(font)
        self.insertar_precio.setObjectName("insertar_precio")
        self.boton_registrar_prenda = QtWidgets.QPushButton(self.centralwidget)
        self.boton_registrar_prenda.setGeometry(QtCore.QRect(214, 470, 351, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.boton_registrar_prenda.setFont(font)
        self.boton_registrar_prenda.setObjectName("boton_registrar_prenda")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PRENDA:"))
        self.label_2.setText(_translate("MainWindow", "TALLA:"))
        self.label_3.setText(_translate("MainWindow", "COLOR:"))
        self.label_4.setText(_translate("MainWindow", "TEMPORADA:"))
        self.label_precio.setText(_translate("MainWindow", "PRECIO:"))
        self.boton_registrar_prenda.setText(_translate("MainWindow", "Registrar prenda"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
