# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_editar.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 600)
        MainWindow.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_precio = QtWidgets.QLabel(self.centralwidget)
        self.label_precio.setGeometry(QtCore.QRect(40, 250, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_precio.setFont(font)
        self.label_precio.setObjectName("label_precio")
        self.insertar_talla = QtWidgets.QLineEdit(self.centralwidget)
        self.insertar_talla.setGeometry(QtCore.QRect(160, 120, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.insertar_talla.setFont(font)
        self.insertar_talla.setObjectName("insertar_talla")
        self.insertar_color = QtWidgets.QLineEdit(self.centralwidget)
        self.insertar_color.setGeometry(QtCore.QRect(160, 160, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.insertar_color.setFont(font)
        self.insertar_color.setObjectName("insertar_color")
        self.insertar_temporada = QtWidgets.QLineEdit(self.centralwidget)
        self.insertar_temporada.setGeometry(QtCore.QRect(160, 210, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.insertar_temporada.setFont(font)
        self.insertar_temporada.setObjectName("insertar_temporada")
        self.insertar_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.insertar_precio.setGeometry(QtCore.QRect(160, 260, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.insertar_precio.setFont(font)
        self.insertar_precio.setObjectName("insertar_precio")
        self.boton_guardar_cambios_prenda = QtWidgets.QPushButton(self.centralwidget)
        self.boton_guardar_cambios_prenda.setGeometry(QtCore.QRect(470, 400, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.boton_guardar_cambios_prenda.setFont(font)
        self.boton_guardar_cambios_prenda.setObjectName("boton_guardar_cambios_prenda")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 60, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.insertar_prenda = QtWidgets.QLineEdit(self.centralwidget)
        self.insertar_prenda.setGeometry(QtCore.QRect(160, 70, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.insertar_prenda.setFont(font)
        self.insertar_prenda.setObjectName("insertar_prenda")
        self.CheckBox_digital = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckBox_digital.setGeometry(QtCore.QRect(370, 340, 70, 17))
        self.CheckBox_digital.setObjectName("CheckBox_digital")
        self.combo_tipo = QtWidgets.QComboBox(self.centralwidget)
        self.combo_tipo.setGeometry(QtCore.QRect(510, 340, 69, 22))
        self.combo_tipo.setObjectName("combo_tipo")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.label_precio_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_precio_2.setGeometry(QtCore.QRect(40, 330, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_precio_2.setFont(font)
        self.label_precio_2.setObjectName("label_precio_2")
        self.radio_standar = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_standar.setGeometry(QtCore.QRect(230, 340, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_standar.setFont(font)
        self.radio_standar.setChecked(True)
        self.radio_standar.setAutoRepeat(False)
        self.radio_standar.setObjectName("radio_standar")
        self.radio_urgente = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_urgente.setGeometry(QtCore.QRect(230, 380, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_urgente.setFont(font)
        self.radio_urgente.setObjectName("radio_urgente")
        self.radio_prioritario = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_prioritario.setGeometry(QtCore.QRect(230, 430, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_prioritario.setFont(font)
        self.radio_prioritario.setObjectName("radio_prioritario")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 340, 31, 16))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 20, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_error_prenda = QtWidgets.QLabel(self.centralwidget)
        self.label_error_prenda.setGeometry(QtCore.QRect(530, 70, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_error_prenda.setFont(font)
        self.label_error_prenda.setText("")
        self.label_error_prenda.setObjectName("label_error_prenda")
        self.label_error_talla = QtWidgets.QLabel(self.centralwidget)
        self.label_error_talla.setGeometry(QtCore.QRect(530, 120, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_error_talla.setFont(font)
        self.label_error_talla.setText("")
        self.label_error_talla.setObjectName("label_error_talla")
        self.label_error_color = QtWidgets.QLabel(self.centralwidget)
        self.label_error_color.setGeometry(QtCore.QRect(530, 170, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_error_color.setFont(font)
        self.label_error_color.setText("")
        self.label_error_color.setObjectName("label_error_color")
        self.label_error_temporada = QtWidgets.QLabel(self.centralwidget)
        self.label_error_temporada.setGeometry(QtCore.QRect(530, 220, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_error_temporada.setFont(font)
        self.label_error_temporada.setText("")
        self.label_error_temporada.setObjectName("label_error_temporada")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "TALLA:"))
        self.label_3.setText(_translate("MainWindow", "COLOR:"))
        self.label_4.setText(_translate("MainWindow", "TEMPORADA:"))
        self.label_precio.setText(_translate("MainWindow", "PRECIO:"))
        self.boton_guardar_cambios_prenda.setText(_translate("MainWindow", "Guardar cambios"))
        self.label_5.setText(_translate("MainWindow", "PRENDA:"))
        self.CheckBox_digital.setText(_translate("MainWindow", "Digital"))
        self.combo_tipo.setItemText(0, _translate("MainWindow", "chico"))
        self.combo_tipo.setItemText(1, _translate("MainWindow", "chica"))
        self.label_precio_2.setText(_translate("MainWindow", "Opciones de envio:"))
        self.radio_standar.setText(_translate("MainWindow", "Envio Standar"))
        self.radio_urgente.setText(_translate("MainWindow", "Envio Urgente"))
        self.radio_prioritario.setText(_translate("MainWindow", "Envio Prioritario"))
        self.label.setText(_translate("MainWindow", "Tipo"))
        self.label_6.setText(_translate("MainWindow", "Datos de prenda a editar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
